# Generated by Django 5.0.2 on 2025-08-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('interview', 'Interview'), ('news', 'Hollywood News'), ('production', 'Film Production'), ('criticism', 'Criticism'), ('documentary', 'Documentary')], default='movie', max_length=20),
        ),
    ]
