# Generated by Django 5.0.2 on 2025-08-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
