# Generated by Django 5.0.2 on 2025-09-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_questionnaire_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='answered_questionnaires',
        ),
        migrations.DeleteModel(
            name='AnsweredQuestionnaire',
        ),
    ]
