# Generated by Django 5.0.2 on 2025-09-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profile_answered_questionnaires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='suggested_movies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
